# Generated by Django 3.1.5 on 2021-01-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerinfo',
            options={'managed': True},
        ),
    ]
