# Generated by Django 3.1.5 on 2021-01-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_type', models.TextField()),
                ('bat_career', models.TextField()),
                ('bat_peak', models.TextField()),
                ('bat_avg', models.TextField()),
                ('bat_rate_career', models.TextField()),
                ('bat_rate_peak', models.TextField()),
                ('bat_rate_avg', models.TextField()),
                ('pit_career', models.TextField()),
                ('pit_peak', models.TextField()),
                ('pit_avg', models.TextField()),
                ('pit_rate_career', models.TextField()),
                ('pit_rate_peak', models.TextField()),
                ('pit_rate_avg', models.TextField()),
            ],
            options={
                'db_table': 'stat_descriptions',
                'managed': True,
            },
        ),
    ]
