# Generated by Django 3.1.5 on 2021-02-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_statdescriptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statdescriptions',
            options={'managed': True, 'verbose_name_plural': 'Stat descriptions'},
        ),
        migrations.AddField(
            model_name='statdescriptions',
            name='career_ip',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='statdescriptions',
            name='career_pas',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='statdescriptions',
            name='peak_ip',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='statdescriptions',
            name='peak_pas',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statdescriptions',
            name='bat_avg',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statdescriptions',
            name='bat_career',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statdescriptions',
            name='bat_peak',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statdescriptions',
            name='bat_rate_avg',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statdescriptions',
            name='bat_rate_career',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statdescriptions',
            name='bat_rate_peak',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statdescriptions',
            name='description_type',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statdescriptions',
            name='pit_avg',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statdescriptions',
            name='pit_career',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statdescriptions',
            name='pit_peak',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statdescriptions',
            name='pit_rate_avg',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statdescriptions',
            name='pit_rate_career',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='statdescriptions',
            name='pit_rate_peak',
            field=models.TextField(default=''),
        ),
    ]
