# Generated by Django 3.1.5 on 2021-01-25 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_auto_20210125_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerinfo',
            options={'managed': False},
        ),
    ]
